namespace eval ::selenium {

    # Defines constants for the standard WebDriver commands.
    #
    # While these constants have no meaning in and of themselves, they are
    # used to marshal commands through a service that implements WebDriver's
    # remote wire protocol:
    #
    # http://code.google.com/p/selenium/wiki/JsonWireProtocol
    #
    # Keep in sync with org.openqa.selenium.remote.DriverCommand

    variable Command

    array set Command {
        STATUS  "status"
        NEW_SESSION  "new session"
        GET_ALL_SESSIONS  "get all sessions"
        DELETE_SESSION  "delete session"
        CLOSE  "close"
        QUIT  "quit"
        GET  "get"
        GO_BACK  "go back"
        GO_FORWARD  "go forward"
        REFRESH  "refresh"
        ADD_COOKIE  "add cookie"
        GET_COOKIE  "get cookie"
        GET_ALL_COOKIES  "get cookies"
        DELETE_COOKIE  "delete cookie"
        DELETE_ALL_COOKIES  "delete all cookies"
        FIND_ELEMENT  "find element"
        FIND_ELEMENTS  "find elements"
        FIND_CHILD_ELEMENT  "find child element"
        FIND_CHILD_ELEMENTS  "find child elements"
        CLEAR_ELEMENT  "clear element"
        CLICK_ELEMENT  "click element"
        SEND_KEYS_TO_ELEMENT  "send keys to element"
        TYPEWRITE  "typewrite"
        SUBMIT_ELEMENT  "submit element"
        UPLOAD_FILE  "upload file"
        GET_CURRENT_WINDOW_HANDLE  "get current window handle"
        GET_WINDOW_HANDLES  "get window handles"
        GET_WINDOW_SIZE  "get window size"
        GET_WINDOW_POSITION  "get window position"
        SET_WINDOW_SIZE  "set window size"
        SET_WINDOW_POSITION  "set window position"
        SWITCH_TO_WINDOW  "switch to window"
        SWITCH_TO_FRAME  "switch to frame"
        SWITCH_TO_PARENT_FRAME  "switch to parent frame"
        GET_ACTIVE_ELEMENT  "get active element"
        GET_CURRENT_URL  "get current url"
        GET_PAGE_SOURCE  "get page source"
        GET_TITLE  "get title"
        EXECUTE_SCRIPT  "execute script"
        GET_ELEMENT_TEXT  "get element text"
        GET_ELEMENT_VALUE  "get element value"
        GET_ELEMENT_TAG_NAME  "get element tag name"
        SET_ELEMENT_SELECTED  "set element selected"
        IS_ELEMENT_SELECTED  "is element selected"
        IS_ELEMENT_ENABLED  "is element enabled"
        IS_ELEMENT_DISPLAYED  "is element displayed"
        GET_ELEMENT_LOCATION  "get element location"
        GET_ELEMENT_LOCATION_ONCE_SCROLLED_INTO_VIEW  "get element location once scrolled into view"
        GET_ELEMENT_SIZE  "get element size"
        GET_ELEMENT_RECT  "get element rect"
        GET_ELEMENT_ATTRIBUTE  "get element attribute"
        GET_ELEMENT_PROPERTY "get element property"
        GET_VALUE_OF_CSS_PROPERTY  "get value of CSS property"
        ELEMENT_EQUALS  "element equals"
        SCREENSHOT  "screenshot"
        ELEMENT_SCREENSHOT "element screenshoot"
        IMPLICIT_WAIT  "implicitly wait"
        EXECUTE_ASYNC_SCRIPT  "execute async script"
        SET_SCRIPT_TIMEOUT  "set script timeout"
        SET_TIMEOUTS  "set timeouts"
        MAXIMIZE_WINDOW  "window maximize"
        W3C_MAXIMIZE_WINDOW  "W3C window maximize"
        GET_LOG  "get log"
        GET_AVAILABLE_LOG_TYPES  "get available log types"

        DISMISS_ALERT  "dismiss alert"
        ACCEPT_ALERT  "accept alert"
        SET_ALERT_VALUE  "set alert value"
        GET_ALERT_TEXT  "get alert text"

        CLICK  "mouse click"
        DOUBLE_CLICK  "mouse double click"
        MOUSE_DOWN  "mouse button down"
        MOUSE_UP  "mouse button up"
        MOVE_TO  "mouse move to"

        SET_SCREEN_ORIENTATION  "set screen orientation"
        GET_SCREEN_ORIENTATION  "get screen orientation"

        SINGLE_TAP  "touch single tap"
        TOUCH_DOWN  "touch down"
        TOUCH_UP  "touch up"
        TOUCH_MOVE  "touch move"
        TOUCH_SCROLL  "touch scroll"
        DOUBLE_TAP  "touch double tap"
        LONG_PRESS  "touch long press"
        FLICK  "touch flick"

        # "HTML 5"
        EXECUTE_SQL  "execute SQL"

        GET_LOCATION  "get location"
        SET_LOCATION  "set location"

        GET_APP_CACHE  "get app cache"
        GET_APP_CACHE_STATUS  "get app cache status"
        CLEAR_APP_CACHE  "clear app cache"

        GET_NETWORK_CONNECTION  "get network connection"
        SET_NETWORK_CONNECTION  "set network connection"

        GET_LOCAL_STORAGE_ITEM  "get local storage item"
        REMOVE_LOCAL_STORAGE_ITEM  "remove local storage item"
        GET_LOCAL_STORAGE_KEYS  "get local storage keys"
        SET_LOCAL_STORAGE_ITEM  "set local storage item"
        CLEAR_LOCAL_STORAGE  "clear local storage"
        GET_LOCAL_STORAGE_SIZE  "get local storage size"

        GET_SESSION_STORAGE_ITEM  "get session storage item"
        REMOVE_SESSION_STORAGE_ITEM  "remove session storage item"
        GET_SESSION_STORAGE_KEYS  "get session storage keys"
        SET_SESSION_STORAGE_ITEM  "set session storage item"
        CLEAR_SESSION_STORAGE  "clear session storage"
        GET_SESSION_STORAGE_SIZE  "get session storage size"

        # "W3C WebDriver"
        W3C_NEW_SESSION "w3c new session"
        W3C_GET_ALL_SESSIONS "w3c get all sessions"
        W3C_DELETE_SESSION "w3c delete session"
        W3C_STATUS "w3c status"
        W3C_QUIT "w3c quit"
        W3C_GET "w3c get"
        W3C_GET_CURRENT_URL "w3c get current url"
        W3C_GO_BACK "w3c go back"
        W3C_FORWARD "w3c forward"
        W3C_REFRESH "w3c refresh"
        W3C_GET_CURRENT_WINDOW_HANDLE "w3c get current window handle"
        W3C_CLOSE_CURRENT_WINDOW_HANDLE "w3c close current window handle"
        W3C_SWITCH_TO_WINDOW "w3c switch to window"
        W3C_GET_WINDOW_HANDLES "w3c get window handles"
        W3C_SWITCH_TO_FRAME "w3c switch to frame"
        W3C_SWITCH_TO_PARENT_FRAME "w3c switch to parent frame"
        W3C_SET_WINDOW_RECT "w3c set window rect"
        W3C_GET_WINDOW_RECT "w3c get window rect"
        W3C_GET_WINDOW_SIZE "w3c get window size"
        W3C_SET_WINDOW_SIZE "w3c set window size"
        W3C_MAXIMIZE_WINDOW "w3c maximize window"
        W3C_MINIMIZE_WINDOW "w3c minimize window"
        W3C_FULLSIZE_WINDOW "w3c fullsize window"
        W3C_FIND_ELEMENT "w3c find element"
        W3C_FIND_ELEMENTS "w3c find elements"
        W3C_FIND_CHILD_ELEMENT "w3c find child element"
        W3C_FIND_CHILD_ELEMENTS "w3c find child elements"
        W3C_GET_ACTIVE_ELEMENT "w3c get active element"
        W3C_IS_ELEMENT_SELECTED "w3c is element selected"
        W3C_GET_ELEMENT_ATTRIBUTE "w3c get element attribute"
        W3C_GET_ELEMENT_PROPERTY "w3c get element property"
        W3C_GET_VALUE_OF_CSS_PROPERTY "w3c get value of css property"
        W3C_GET_ELEMENT_TEXT "w3c get element text"
        W3C_GET_ELEMENT_TAG_NAME "w3c get element tag name"
        W3C_GET_ELEMENT_RECT "w3c get element rect"
        W3C_IS_ELEMENT_ENABLED "w3c is element enabled"
        W3C_CLICK_ELEMENT "w3c click element"
        W3C_CLEAR_ELEMENT "w3c clear element"
        W3C_SEND_KEYS_TO_ELEMENT "w3c send keys to element"
        W3C_GET_PAGE_SOURCE "w3c get page source"

        # "Additionals or Duplicates I Havent Vetted"
        W3C_EXECUTE_SCRIPT  "w3c execute script"
        W3C_EXECUTE_ASYNC_SCRIPT  "w3c execute async script"
        W3C_GET_ALL_COOKIES  "w3c get all cookies"
        W3C_GET_NAMED_COOKIE "w3c get named cookie"
        W3C_ADD_COOKIE "w3c add cookie"
        W3C_DELETE_COOKIE  "w3c delete cookie"
        W3C_DELETE_ALL_COOKIES  "w3c delete all cookieS"
        W3C_PERFORM_ACTIONS "w3c perform actions"
        W3C_RELEASE_ACTIONS "w3c release actions"
        W3C_DISMISS_ALERT "w3c dismiss alert"
        W3C_ACCEPT_ALERT "w3c accept alert"
        W3C_GET_ALERT_TEXT "w3c get alert text"
        W3C_SET_ALERT_VALUE "w3c set alert value"
        W3C_SCREENSHOT "w3c screenshot"
        W3C_ELEMENT_SCREENSHOT "w3c element screenshot"
        W3C_SET_TIMEOUTS "w3c set timeouts"
        W3C_GET_TIMEOUTS "w3c get timeouts"
        W3C_GET_TITLE "w3c get title"
        # #
    }

}
